### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by the-wondersmith** [atxsinn3r/BinjaStringsInCode#1]
Apologies in advance for ~~slightly~~ abusing the Issues system to ask such a seemingly inane question.

I'd like to use your plugin, but I can't find documentation for how C++ plugins are supposed to be installed in Binary Ninja. Do I need to manually create a `plugin.json` and `__init__.py`? If so, what needs to be imported at the top of `__init__.py`?

**Comment by atxsinn3r** [comment]
Hi @the-wondersmith,

It's very simple; actually easier than the Python plugin. All you have to do is drag and drop libStringRefsInCode.dylib to `~/Library/Application\ Support/Binary\ Ninja/plugins/`, and then start Binary Ninja. The plugin should be found under the Tools menu in the UI.

Cheers!

**Comment by the-wondersmith** [comment]
> Hi @the-wondersmith,
> 
> It's very simple; actually easier than the Python plugin. All you have to do is drag and drop libStringRefsInCode.dylib to `~/Library/Application\ Support/Binary\ Ninja/plugins/`, and then start Binary Ninja. The plugin should be found under the Tools menu in the UI.
> 
> Cheers!

Thank you!
